-- BAI TOAN 1:
SELECT a.F_NAME, a.L_NAME, b.START_DATE
FROM hr.EMPLOYEES a
LEFT JOIN hr.JOB_HISTORY b ON a.EMP_ID = b.EMPL_ID

-- BAI TOAN 2:
SELECT a.F_NAME, a.L_NAME, b.START_DATE, c.JOB_TITLE
FROM hr.EMPLOYEES a
LEFT JOIN hr.JOB_HISTORY b ON a.EMP_ID = b.EMPL_ID
LEFT JOIN hr.JOBS c ON c.JOB_IDENT = b.JOBS_ID
WHERE b.DEPT_ID = 5;
-- BAI TOAN 3: 
SELECT a.EMP_ID, a.F_NAME, a.L_NAME, b.DEPT_ID_DEP, b.DEP_NAME
FROM hr.EMPLOYEES a
LEFT OUTER JOIN hr.DEPARTMENTS b ON a.DEP_ID = b.DEPT_ID_DEP

-- BAI TOAN 4:
SELECT a.EMP_ID, a.L_NAME, a.DEP_ID, b.DEP_NAME
FROM hr.EMPLOYEES a
LEFT JOIN hr.DEPARTMENTS b ON a.DEP_ID = b.DEPT_ID_DEP
WHERE YEAR(a.B_DATE) < 1980;

-- BAI TOAN 5: 
SELECT a.EMP_ID, a.L_NAME, a.DEP_ID, b.DEP_NAME
FROM hr.EMPLOYEES a
INNER JOIN hr.DEPARTMENTS b ON a.DEP_ID = b.DEPT_ID_DEP
WHERE YEAR(a.B_DATE) < 1980;

-- BAI TOAN 6:
SELECT a.F_NAME, a.L_NAME, b.DEP_NAME
FROM hr.EMPLOYEES a
LEFT OUTER JOIN hr.DEPARTMENTS b ON a.DEP_ID = b.DEPT_ID_DEP;

-- BAI TOAN 7: 
select E.F_NAME,E.L_NAME,D.DEPT_ID_DEP, D.DEP_NAME
from EMPLOYEES AS E 
LEFT OUTER JOIN DEPARTMENTS AS D ON E.DEP_ID=D.DEPT_ID_DEP AND E.SEX = 'M'
UNION ALL
select E.F_NAME,E.L_NAME,D.DEPT_ID_DEP, D.DEP_NAME
from EMPLOYEES AS E 
RIGHT OUTER JOIN DEPARTMENTS AS D ON E.DEP_ID=D.DEPT_ID_DEP AND E.SEX = 'M';
    
